packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - '@types/react-dom@19.2.5'
  - lucide-react@1.34.0
